name: "Guidepup Setup"
description: "Setup your environment for screen-reader automation."
author: "Craig Morten"
branding:
  icon: "check-circle"
  color: "gray-dark"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        sudo "/Library/Application Support/VMware Tools/vmware-resolutionSet" 1440 900
        sleep 5
    - shell: nodejs
      run: "index.js"
