name: "Guidepup Setup"
description: "Setup your environment for screen reader test automation."
author: "Craig Morten"
branding:
  icon: "check-circle"
  color: "gray-dark"
inputs:
  resolutionWidth:
    description: "Screen resolution width to use. macos agents only."
    required: false
    default: "1920"
  resolutionHeight:
    description: "Screen resolution height to use. macos agents only."
    required: false
    default: "1080"
  record:
    description: "Whether to screen-record the setup flow and save to a './recordings/' folder in the current working directory. macos agents only."
    required: false
    default: false
  ignoreTccDb:
    description: "Ignore TCC.db updates if not possible or required for your environment. Default is not to ignore. macos agents only."
    required: false
    default: false
  nvdaInstallDir:
    description: "Specify a custom location for where to install NVDA. Default is to install to a temporary directory. windows agents only."
    required: false
    default: ""
runs:
  using: "node16"
  main: "index.js"
